### ISSUE TITLE
`yarn imp` => Cannot find module 'src/import.src'

### ISSUE THREAD

**Issue by roschaefer** [demokratie-live/bundestag.io#51]
Cloning the repo and following the README gives me:
```
➜  bundestag.io git:(master) yarn imp
yarn run v1.6.0
$ babel-node src/import.js
internal/modules/cjs/loader.js:550
    throw err;
    ^
Error: Cannot find module '/SSD/Democracy/bundestag.io/src/import.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at Object.<anonymous> (/SSD/Democracy/bundestag.io/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ulfgebhardt** [comment]
Der Import-Job wird automatisch per Cron gestartet, wenn bio läuft. Ich schau mir das an - der yarn imp befehl wurde lange nicht mehr benutzt - sollte aber importAll sein meine ich. Morgen kann ich dir mehr sagen ;-)
